// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    RpcBar: typeof import('./src/components/RpcBar.vue')['default']
    RpcLogs: typeof import('./src/components/RpcLogs.vue')['default']
    RpcMethodArgs: typeof import('./src/components/RpcMethodArgs.vue')['default']
    RpcMethods: typeof import('./src/components/RpcMethods.vue')['default']
    RpcTopBar: typeof import('./src/components/RpcTopBar.vue')['default']
    Wallet: typeof import('./src/components/Wallet.vue')['default']
  }
}

export {}
